#!/bin/bash

set -ouex pipefail

# Repository setup
sed -i 's/main/main contrib non-free non-free-firmware/' /etc/apt/sources.list.d/*

# Initial update
apt-get update -y

# Install Plymouth for boot splash
apt-get install -y \
	plymouth \
	plymouth-themes \
	plymouth-label

# install firmware packages
echo "firmware-ipw2x00 firmware-ipw2x00/license/accepted boolean true" | debconf-set-selections
echo "firmware-ivtv firmware-ivtv/license/accepted boolean true" | debconf-set-selections
apt-get install -y \
	atmel-firmware \
	bluez-firmware \
	dahdi-firmware-nonfree \
	firmware-amd-graphics \
	firmware-ast \
	firmware-ath9k-htc \
	firmware-atheros \
	firmware-bnx2 \
	firmware-bnx2x \
	firmware-brcm80211 \
	firmware-carl9170 \
	firmware-cavium \
	firmware-cirrus \
	firmware-intel-graphics \
	firmware-intel-misc \
	firmware-intel-sound \
	firmware-ipw2x00 \
	firmware-ivtv \
	firmware-iwlwifi \
	firmware-libertas \
	firmware-linux-free \
	firmware-linux-nonfree \
	firmware-linux \
	firmware-marvell-prestera \
	firmware-mediatek \
	firmware-misc-nonfree \
	firmware-myricom \
	firmware-netronome \
	firmware-netxen \
	firmware-nvidia-graphics \
	firmware-qlogic \
	firmware-realtek \
	firmware-siano \
	firmware-sof-signed \
	firmware-zd1211

# Install GNOME Desktop
apt-get install -y \
	gnome-core \
	gnome-initial-setup \
	tuned \
	tuned-ppd \
	ptyxis \
	pipewire \
	dbus-broker

mkdir -p /usr/share/snow
apt list --installed > /usr/share/snow/desktop-packages.txt

# Remove unwanted bits of GNOME Core
apt purge -y \
	evolution \
	firefox-esr \
	gnome-calculator \
	gnome-calendar \
	gnome-characters \
	gnome-clocks \
	gnome-connections \
	gnome-contacts \
	gnome-font-viewer \
	gnome-maps \
	gnome-shell-extension-manager \
	gnome-software \
	gnome-system-monitor \
	gnome-text-editor \
	gnome-weather \
	loupe \
	papers \
	totem \
	yelp

apt list --installed > /usr/share/snow/desktop-packages.after-cleanup.txt

# Build Initramfs
KERNEL_VERSION="$(basename "$(find /usr/lib/modules -maxdepth 1 -type d | grep -v -E "*.img" | tail -n 1)")"
dracut --force --no-hostonly --reproducible --zstd --verbose \
	--kver "$KERNEL_VERSION" "/usr/lib/modules/$KERNEL_VERSION/initramfs.img"

# remove machine-id
rm -f /etc/machine-id
