#!/bin/bash

set -ouex pipefail

# Repository setup
sed -i 's/main/main contrib non-free non-free-firmware/' /etc/apt/sources.list.d/*

# Initial update
apt-get update -y

# Install Plymouth for boot splash
apt-get install -y \
	plymouth \
	plymouth-themes \
	plymouth-label

# install firmware packages
echo "firmware-ipw2x00 firmware-ipw2x00/license/accepted boolean true" | debconf-set-selections
echo "firmware-ivtv firmware-ivtv/license/accepted boolean true" | debconf-set-selections
apt-get install -y \
	atmel-firmware \
	bluez-firmware \
	dahdi-firmware-nonfree \
	firmware-amd-graphics \
	firmware-ast \
	firmware-ath9k-htc \
	firmware-atheros \
	firmware-bnx2 \
	firmware-bnx2x \
	firmware-brcm80211 \
	firmware-carl9170 \
	firmware-cavium \
	firmware-cirrus \
	firmware-intel-graphics \
	firmware-intel-misc \
	firmware-intel-sound \
	firmware-ipw2x00 \
	firmware-ivtv \
	firmware-iwlwifi \
	firmware-libertas \
	firmware-linux-free \
	firmware-linux-nonfree \
	firmware-linux \
	firmware-marvell-prestera \
	firmware-mediatek \
	firmware-misc-nonfree \
	firmware-myricom \
	firmware-netronome \
	firmware-netxen \
	firmware-nvidia-graphics \
	firmware-qlogic \
	firmware-realtek \
	firmware-siano \
	firmware-sof-signed \
	firmware-zd1211

# Install GNOME Desktop
apt-get install -y \
	gnome-core \
	gnome-initial-setup \
	tuned \
	tuned-ppd \
	switcheroo-control \
	ptyxis \
	pipewire \
	dbus-broker \
	mesa-va-drivers \
	intel-media-va-driver-non-free

# Remove unwanted bits of GNOME Core
apt purge -y \
	gnome-session-xsession \
	baobab \
	evince \
	evolution \
	firefox-esr \
	gnome-calculator \
	gnome-calendar \
	gnome-characters \
	gnome-clocks \
	gnome-connections \
	gnome-contacts \
	gnome-font-viewer \
	gnome-logs \
	gnome-maps \
	gnome-shell-extension-manager \
	gnome-software \
	gnome-system-monitor \
	gnome-text-editor \
	gnome-weather \
	simple-scan \
	loupe \
	papers \
	totem \
	yelp

# Get package list
mkdir -p /usr/share/snow
apt list --installed > /usr/share/snow/desktop-packages.txt

# Update build information in os-release
sed -i "s/^BUILD_ID=.*/BUILD_ID=\"$BUILD_ID\"/" /usr/lib/os-release
