#!/bin/bash

set -ouex pipefail

# Initial update
apt-get update -y

# Install GNOME Desktop
apt-get install -y \
  gnome-core \
  gnome-initial-setup \
  ptyxis \
  pipewire \
  dbus-broker

mkdir -p /usr/share/snow
apt list --installed > /usr/share/snow/desktop-packages.txt

# Remove unwanted bits of GNOME Core
apt purge -y \
  evolution \
  firefox-esr \
  gnome-calculator \
  gnome-calendar \
  gnome-characters \
  gnome-clocks \
  gnome-connections \
  gnome-contacts \
  gnome-font-viewer \
  gnome-maps \
  gnome-shell-extension-manager \
  gnome-software \
  gnome-system-monitor \
  gnome-text-editor \
  gnome-weather \
  papers \
  totem \
  yelp

apt list --installed > /usr/share/snow/desktop-packages.after-cleanup.txt
